name: covid_bot
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  teledart: ^0.0.50
  http: ^0.12.2
  get_it: ^4.0.4
  intl: ^0.16.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
